-- phpMyAdmin SQL Dump
-- version 4.8.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 09 Des 2018 pada 06.35
-- Versi server: 10.1.34-MariaDB
-- Versi PHP: 7.2.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `wiki`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `article`
--

CREATE TABLE `article` (
  `id` int(11) NOT NULL,
  `article_text` text NOT NULL,
  `author` text NOT NULL,
  `author_edit` text,
  `image` text NOT NULL,
  `title` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `article`
--

INSERT INTO `article` (`id`, `article_text`, `author`, `author_edit`, `image`, `title`) VALUES
(1, 'PHP\r\nPHP-logo.svg\r\nParadigm	Imperative, functional, object-oriented, procedural, reflective\r\nDesigned by	Rasmus Lerdorf\r\nDeveloper	The PHP Development Team, Zend Technologies\r\nFirst appeared	1995; 23 years ago[1]\r\nStable release	\r\n7.2.12[2] / November 8, 2018; 27 days ago\r\nPreview release	\r\n7.3.0RC6[3] / November 22, 2018; 13 days ago\r\nTyping discipline	Dynamic, weak\r\nsince version 7.0:\r\n\r\nGradual[4]\r\nImplementation language	C (primarily; some components C++)\r\nOS	Unix-like, Windows\r\nLicense	PHP License (most of Zend engine under Zend Engine License)\r\nFilename extensions	.php, .phtml, .php3, .php4, .php5, .php7, .phps, .php-s, .pht\r\nWebsite	secure.php.net\r\nMajor implementations\r\nZend Engine, HHVM, Phalanger, Quercus, Parrot\r\nInfluenced by\r\nPerl, C, C++, Java, Tcl[1]\r\nInfluenced\r\nHack\r\n PHP Programming at Wikibooks\r\nPHP: Hypertext Preprocessor (or simply PHP) is a server-side scripting language designed for Web development, and also used as a general-purpose programming language. It was originally created by Rasmus Lerdorf in 1994;[5] the PHP reference implementation is now produced by The PHP Group.[6] PHP originally stood for Personal Home Page,[5] but it now stands for the recursive initialism PHP: Hypertext Preprocessor.[7]\r\n\r\nPHP code may be embedded into HTML code, or it can be used in combination with various web template systems, web content management systems, and web frameworks. PHP code is usually processed by a PHP interpreter implemented as a module in the web server or as a Common Gateway Interface (CGI) executable. The web server combines the results of the interpreted and executed PHP code, which may be any type of data, including images, with the generated web page. PHP code may also be executed with a command-line interface (CLI) and can be used to implement standalone graphical applications.[8]', 'Admin', 'Admin', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLVlYfdh2Wyotu5ARpshBzkayBENicW-NmtIzKeJW9fPKGQXeQ', 'PHP for Everyone'),
(2, 'Java is a general-purpose computer-programming language that is concurrent, class-based, object-oriented,[15] and specifically designed to have as few implementation dependencies as possible. It is intended to let application developers \"write once, run anywhere\" (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of computer architecture. As of 2016, Java is one of the most popular programming languages in use,[18][19][20][21] particularly for client-server web applications, with a reported 9 million developers.[22] Java was originally developed by James Gosling at Sun Microsystems (which has since been acquired by Oracle Corporation) and released in 1995 as a core component of Sun Microsystems\' Java platform. The language derives much of its syntax from C and C++, but it has fewer low-level facilities than either of them.', 'Lala', NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr41RfcQZ1BGeeRvyRRh3SKLCbPpvNMgJczdWHQbK3cBlpBFuz', 'Code Once Run Everywhere'),
(5, 'Google LLC[5] adalah sebuah perusahaan multinasional Amerika Serikat yang berkekhususan pada jasa dan produk Internet. Produk-produk tersebut meliputi teknologi pencarian, komputasi web, perangkat lunak, dan periklanan daring.[6] Sebagian besar labanya berasal dari AdWords. <br> <br>\r\n\r\nGoogle didirikan oleh Larry Page dan Sergey Brin saat masih mahasiswa Ph.D. di Universitas Stanford. Mereka berdua memegang 16 persen saham perusahaan. Mereka menjadikan Google sebagai perusahaan swasta pada tanggal 4 September 1998. Pernyataan misinya adalah \"mengumpulkan informasi dunia dan membuatnya dapat diakses dan bermanfaat oleh semua orang\",[9] dan slogan tidak resminya adalah \"Don\'t be evil\".[10][11] Pada tahun 2006, kantor pusat Google pindah ke Mountain View, California.<br> <br>\r\n\r\nSejak didirikan, pertumbuhan perusahaan yang cepat telah menghasilkan berbagai produk, akuisisi, dan kerja sama di bidang mesin pencari inti Google. Perusahaan ini menawarkan perangkat lunak produktivitas daring (dalam jaringan), termasuk surat elektronik (surel), paket aplikasi perkantoran, dan jejaring sosial. Produk-produk komputer mejanya meliputi aplikasi untuk menjelajah web, mengatur dan menyunting foto, dan pesan instan. Perusahaan ini memprakarsai pengembangan sistem operasi Android untuk telepon genggam dan Google Chrome OS[12] untuk jajaran netbook Chromebook. Google sudah beralih ke perangkat keras komunikasi. Mereka bekerja sama dengan berbagai produsen elektronik besar untuk memproduksi perangkat Nexus-nya dan mengakuisisi Motorola Mobility pada Mei 2012.[13] Tahun 2012, infrastruktur serat optik dipasang di Kansas untuk memfasilitasi layanan Internet pita lebar Google Fiber.<br> <br>\r\n', 'wer', 'wer', 'https://www.digitalmicdrop.com/wp-content/uploads/2017/05/google-learning.gif', 'Belajar Dari Google'),
(6, 'Once Kotlin received Google’s support, the sheer excitement of Kotlin fans wasn’t the only reaction to follow. Those not familiar with Kotlin were quite concerned about its compatibility/interoperability level with Java, the average time necessary to get the hang of it, as well as the advantages of using Kotlin in general.<br><br>\r\n\r\nIn their attempts to explain and introduce the language in the shortest and clearest way possible, many Kotlin developers referred to a 3-year-old parallel between Kotlin and the second official language of iOS – Swift. Calling Kotlin “the Swift of Android” did make things easier and helped to create an image for the language. Yet this image also provoked arguments in the iOS community, as some iOS developers didn’t find the comparison flattering and saw Kotlin as a mere copycat.<br><br>\r\n\r\nAt the very least, it should be noted that while Swift appeared in 2013, Kotlin originated back in 2011. Hence, even though comparing Kotlin to Swift (in this exact order) can be convenient due to Swift’s earlier introduction to a wide audience, any ‘copycat’ attitudes towards Kotlin aren’t justified. \r\nStill, does the comparison stand? If yes, how far does the similarity stretch? And does its existence hint at the fact that delivering apps for both iOS and Android natively can become easier and faster in the future? ScienceSoft\'s huge experience in mobile app development services allows to speculate at this point. Let’s look into it.', 'Mamskiq', 'Mamskiq', 'https://res.cloudinary.com/practicaldev/image/fetch/s--Arz4PKgH--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/1ckvhgs9qeq92xdaqjas.png', 'Kotlin vs Swift'),
(7, 'Anko is a Kotlin library which makes Android application development faster and easier. It makes your code clean and easy to read, and lets you forget about rough edges of the Android SDK for Java\r\nIt states that “It makes your code clean and easy to read” … wait, we’re using kotlin to make our code in Android more clean and easy to read, right ? so, if you’re using Anko. That means your code will be more beautiful… hmm, interesting, isn’t it ?<br><br>\r\n\r\nDid you find any blocks from those following code, right ? these are one of the basic function that comes from Anko library ???? … so, what is it ? at the first blocks, we set a content view of android layout using Anko DSL components. what is it looks like ? Let see another basic function from Anko, like how to define a logger… usually we define a logger using android.util.Log right ? and we have to declare the tag using our current class… like the following example', 'Andi Wijaya', NULL, 'https://cdn-images-1.medium.com/max/1600/1*ipZA_aypxI1notOgR6yjyw.png', 'Anko Kotlin - Codeless Build More'),
(8, 'Progressive Web Apps are user experiences that have the reach of the web, and are:<br>\r\nReliable - Load instantly and never show the downasaur, even in uncertain network conditions.<br>\r\nFast - Respond quickly to user interactions with silky smooth animations and no janky scrolling.<br>\r\nEngaging - Feel like a natural app on the device, with an immersive user experience.<br>\r\nThis new level of quality allows Progressive Web Apps to earn a place on the user\'s home screen.<br><br>\r\n\r\nReliable\r\nWhen launched from the user’s home screen, service workers enable a Progressive Web App to load instantly, regardless of the network state.\r\nA service worker, written in JavaScript, is like a client-side proxy and puts you in control of the cache and how to respond to resource requests. By pre-caching key resources you can eliminate the dependence on the network, ensuring an instant and reliable experience for your users.', 'Yulias', NULL, 'https://cdn-images-1.medium.com/max/1600/1*hWVmsnBY6Fr6OoNvIU5pmg.png', 'Next Level of Mobile Web Application'),
(9, 'Node.js is an open-source, cross-platform JavaScript run-time environment that executes JavaScript code outside of a browser. Typically, JavaScript is used primarily for client-side scripting, in which scripts written in JavaScript are embedded in a webpage\'s HTML and run client-side by a JavaScript engine in the user\'s web browser. Node.js lets developers use JavaScript to write Command Line tools and for server-side scripting—running scripts server-side to produce dynamic web page content before the page is sent to the user\'s web browser. Consequently, Node.js represents a \"JavaScript everywhere\" paradigm,[6] unifying web application development around a single programming language, rather than different languages for server side and client side scripts.<br><br>\r\n\r\nThough .js is the conventional filename extension for JavaScript code, the name \"Node.js\" does not refer to a particular file in this context and is merely the name of the product. Node.js has an event-driven architecture capable of asynchronous I/O. These design choices aim to optimize throughput and scalability in web applications with many input/output operations, as well as for real-time Web applications (e.g., real-time communication programs and browser games).<br><br>\r\n\r\nThe Node.js distributed development project, governed by the Node.js Foundation,[8] is facilitated by the Linux Foundation\'s Collaborative Projects program.<br><br>\r\n\r\nCorporate users of Node.js software include GoDaddy,[10] Groupon,[11] IBM,[12] LinkedIn,[13][14] Microsoft,[15][16] Netflix,[17] PayPal,[18][19] Rakuten, SAP,[20] Voxer,[21] Walmart,[22] and Yahoo!.<br>', 'Kasta', NULL, 'https://visualstudio.microsoft.com/wp-content/uploads/2016/06/Nodejs-2-562x309@2x-op-800x404.png', 'Node is Faster than Ever'),
(10, 'Go (often referred to as Golang[12]) is a programming language designed by Google[13] engineers Robert Griesemer, Rob Pike, and Ken Thompson.[10] Go is statically typed, compiled, and syntactically similar to C, with the added benefits of memory safety, garbage collection, structural typing,[4] and CSP-style concurrency.[14] The compiler, tools, and source code are all free and open source.<br><br>\r\n\r\nThe designers cited their shared dislike of C++ as a primary motivation for designing a new language.<br><br>\r\n\r\nGo was publicly announced in November 2009,[22] and version 1.0 was released in March 2012.[23][24] Go is widely used in production at Google[25] and in many other organizations and open-source projects.<br><br>\r\n\r\nIn April 2018, the original logo (Gopher mascot) was replaced with a stylized GO slanting right with trailing streamlines. However, the mascot remained the same.<br><br>\r\n\r\nIn August 2018, the Go principal contributors published two ?draft designs? for new language features, Generics and Error Handling, and asked Go users to submit feedback on them.[27][28] Lack of support for generic programming and the verbosity of error handling in Go 1.x had drawn considerable criticism.<br><br>', 'Michael P', NULL, 'https://www.archer.com.mt/wp-content/uploads/golang-gopher.png', 'Made by Google'),
(11, 'oogle sedang mengadakan program untuk melatih 100,000 developer seluler di Indonesia. Dengan membuka sekian banyak prakarsa di seluruh mitra pelatihan dan universitas, Google ingin membuat pendidikan developer Android kelas dunia bisa diakses oleh semua pelajar dan developer di seluruh Indonesia.<br><br>\r\n\r\nGoogle sedang membuat kursus pelatihan berbasis kelas baru untuk mengajarkan keahlian development Android kepada para mahasiswa di Indonesia. Kursus, yang akan disediakan melalui lisensi Creative Commons, akan tersedia dalam Bahasa Indonesia maupun Bahasa Inggris.<br><br>\r\n\r\nKursus ini dirancang untuk mahasiswa ilmu komputer, dan memandu mereka melalui pembuatan aplikasi sambil mengembangkan keahlian yang diperlukan untuk mendapatkan pekerjaan tingkat dasar sebagai developer Android. Setelah menyelesaikan kursus dan membuat aplikasi di kursus, mereka akan siap untuk mengikuti ujian Associate Android Developer Certification.<br><br>', 'Andi Wijaya', NULL, 'https://cdn-images-1.medium.com/max/900/1*fDv4ftmFy4VkJmMR7VQmEA.png', 'DSC for Community'),
(12, 'GitHub was developed by Chris Wanstrath, PJ Hyett, Tom Preston-Werner and Scott Chacon using Ruby on Rails, and started in February 2008. The company, GitHub, Inc., has existed since 2007 and is located in San Francisco.<br><br>\r\n\r\n\r\nThe shading of the map illustrates the number of users as a proportion of each country\'s Internet population. The circular charts surrounding the two hemispheres depict the total number of GitHub users (left) and commits (right) per country.\r\nOn February 24, 2009, GitHub team members announced, in a talk at Yahoo! headquarters, that within the first year of being online, GitHub had accumulated over 46,000 public repositories, 17,000 of which were formed in the previous month alone. At that time, about 6,200 repositories had been forked at least once and 4,600 had been merged.<br><br>\r\n\r\nOn July 5, 2009, GitHub announced that the site was now harnessed by over 100,000 users. On July 27, 2009, in another talk delivered at Yahoo!, Tom Preston-Werner announced that GitHub had grown to host 90,000 unique public repositories, 12,000 having been forked at least once, for a total of 135,000 repositories.<br><br>\r\n\r\nOn July 25, 2010, GitHub announced that it was hosting 1 million repositories.[14] On April 20, 2011, GitHub announced that it was hosting 2 million repositories.<br><br>', 'Andi Wijaya', NULL, 'https://assets-cdn.github.com/images/modules/open_graph/github-octocat.png', 'Contribute with Github');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `article`
--
ALTER TABLE `article`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `article`
--
ALTER TABLE `article`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
